# LoLaeMon (로라에몽 : LLM 기반 도라에몽)

현대 세계(2020년대)의 문제를 해결하기 위해, 존재하지 않는 '미래의 비밀 도구'를 논리적(혹은 엉뚱하게)으로 발명하고 그 결과를 텍스트로 시뮬레이션함

한국어-영어 번역 말뭉치(기술과학)
- 출처 : https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=data&dataSetSn=124

In [5]:
from dotenv import load_dotenv
load_dotenv()

True

### 전처리

#### lag용 데이터확인

In [8]:
import pandas as pd
# 150만개의 데이터에서 샘플 데이터 (14만개의 샘플 데이터 확인)
tech_df = pd.read_csv('./data/1113_tech_test_set_149404.csv',sep=',')
print('\n', tech_df.info())
tech_df.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149404 entries, 0 to 149403
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   sn               149404 non-null  object
 1   file_name        149404 non-null  object
 2   data_set         149404 non-null  object
 3   domain           149404 non-null  object
 4   subdomain        149404 non-null  object
 5   source           149404 non-null  object
 6   ko               149404 non-null  object
 7   mt               149404 non-null  object
 8   en               149404 non-null  object
 9   source_language  149404 non-null  object
 10  target_language  149404 non-null  object
 11  license          149404 non-null  object
 12  style            149404 non-null  object
dtypes: object(13)
memory usage: 14.8+ MB

 None

,sn,file_name,data_set,domain,subdomain,source,ko,mt,en,source_language,target_language,license,style
0,TNS01A11114,특허_3주_1020150154505,기술과학,기계,동력기관,특허정보원,상기 장부 절인은 상기 직선 구간의 중심을 기준으로 대칭된 형상을 가질 수 있다.,The tenon pickled may have a shape symmetrical...,The longer cutting edge may have a symmetrical...,ko,en,open,문어체
1,TNS01H38275,특허_13주_1020170089843,기술과학,기계,재료공학,특허정보원,"하나의 예시에서, 상기 블록 공중합체는, 상기 제 블록으로서 전술한 화학식 1로 표...","In one example, the block copolymer may includ...","In one example, the block copolymer may includ...",ko,en,open,문어체

In [9]:
# 포함 기술 정보 확인  (컬럼에 포함된 정보)
print(tech_df['data_set'].unique()) # 큰 카테고리
print(tech_df['domain'].unique()) # 도메인 분야
print(tech_df['subdomain'].unique()) # 세부 기술
print(tech_df['source'].unique()) # 출처

tech_df.iloc[3,[2,3,4,6]]

['기술과학']
['기계' '전자' '의학' 'ICT' '전기']
['동력기관' '재료공학' '무선통신' '디스플레이' '내과학' '의공학' '간호학' '통신' '에너지' '배터리' '병리학'
 '가정의학' '외과학' '빅데이터' '열처리' '컴퓨터' '설비' '반도체']
['특허정보원' '한국학술정보' '한국연구재단']

data_set                                                  기술과학
domain                                                      전자
subdomain                                                디스플레이
ko           본 발명의 실시예에 있어서, 상기 패널의 레이아웃 및 상기 재단라인은 비선형 라인을...
Name: 3, dtype: object

#### 결측치 확인

In [10]:
tech_df.isna().sum()

sn                 0
file_name          0
data_set           0
domain             0
subdomain          0
source             0
ko                 0
mt                 0
en                 0
source_language    0
target_language    0
license            0
style              0
dtype: int64

#### 기술 document 생성

In [13]:
# 도메인 분야 + 세부 기술 + 간단한 기술 정보 텍스트
tech_df['tech_text'] = tech_df['domain'] + ' ' + tech_df['subdomain'] + ' ' + tech_df['ko']
tech_df['tech_text'].head()

0    기계 동력기관 상기 장부 절인은 상기 직선 구간의 중심을 기준으로 대칭된 형상을 가...
1    기계 재료공학 하나의 예시에서, 상기 블록 공중합체는, 상기 제 블록으로서 전술한 ...
2    전자 무선통신 후면 커버(130a)는 미들 커버(120a) 상에 배치되어 결합되고,...
3    전자 디스플레이 본 발명의 실시예에 있어서, 상기 패널의 레이아웃 및 상기 재단라인...
4    의학 내과학 증상을 일으키지 않은 회충 충체를 내시경적으로 반드시 제거해야만 하는 ...
Name: tech_text, dtype: object

### Chroma DB(아이디어 재료 창고) &
###  HuggingFaceEmbeddings을 이용한 무료 vector store 생성
- 외부 DB를 사용하면 거의 돈이 안듦
- open api를 이용하면 임베딩할때 돈많이 드는듯함
- model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

#### Embedding
- sentence-transformers/
paraphrase-multilingual-MiniLM-L12-v2'

In [ ]:
from langchain_community.embeddings import HuggingFaceEmbeddings
import torch
import chromadb
from tqdm import tqdm

# 폴더에 임베딩 데이터 저장 설정
client = chromadb.PersistentClient(path="./lolaemon_chroma_db")
collection = client.get_or_create_collection(name="lolaemon")

device = 'cuda' if torch.cuda.is_available() else 'cpu'
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

# 메타데이터에 들어갈 정보 모두 리스트로 바꿔주기
all_texts = tech_df['tech_text'].astype(str).tolist()
all_domains = tech_df['domain'].astype(str).tolist()
all_subdomains = tech_df['subdomain'].astype(str).tolist()
all_sources = tech_df['source'].astype(str).tolist()
all_ko = tech_df['ko'].astype(str).tolist()

chunk_size = 5461 # 5461건씩 묶어서 처리 (colab 최대)
for i in tqdm(range(0, len(all_texts), chunk_size)):
    end = i + chunk_size
    batch_texts = all_texts[i:end]
    batch_embedding = embedding_model.embed_documents(batch_texts)
    metadata = [{'domain': all_domains[j], 'subdomain': all_subdomains[j],
     'source':all_sources[j], 'origin tech text': all_ko[j]} for j in range(i, min(end, len(all_texts)))] # 딱짤라지지않아서 마지막 데이터까지 넣어주기 위함
    batch_ids = [str(j) for j in range(i, min(end, len(all_texts)))]
    
    collection.add(ids = batch_ids, embeddings = batch_embedding, documents = batch_texts, metadatas = metadata)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
100%|██████████| 28/28 [06:13<00:00, 13.35s/it]

In [21]:
# embedding 확인
batch_size = 500

all_data = []

for i in range(0, 140000, batch_size):
    batch = collection.get(
        limit=batch_size,
        offset=i
    )
    all_data.append(batch)

In [28]:
collection.get(limit=2) # 배치말고 1개만보기

{'ids': ['0', '1'],
 'embeddings': None,
 'documents': ['기계 동력기관 상기 장부 절인은 상기 직선 구간의 중심을 기준으로 대칭된 형상을 가질 수 있다.',
  '기계 재료공학 하나의 예시에서, 상기 블록 공중합체는, 상기 제 블록으로서 전술한 화학식 1로 표시되는 반복 단위를 포함할 수 있다.'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [{'source': '특허정보원',
   'subdomain': '동력기관',
   'origin tech text': '상기 장부 절인은 상기 직선 구간의 중심을 기준으로 대칭된 형상을 가질 수 있다.',
   'domain': '기계'},
  {'source': '특허정보원',
   'domain': '기계',
   'subdomain': '재료공학',
   'origin tech text': '하나의 예시에서, 상기 블록 공중합체는, 상기 제 블록으로서 전술한 화학식 1로 표시되는 반복 단위를 포함할 수 있다.'}]}

In [26]:
!zip -r lolaemon_chroma_db.zip ./lolaemon_chroma_db

  adding: lolaemon_chroma_db/ (stored 0%)
  adding: lolaemon_chroma_db/chroma.sqlite3 (deflated 61%)
  adding: lolaemon_chroma_db/94eeeb1b-8d46-4fbf-8b43-cba8e9ed5f0f/ (stored 0%)
  adding: lolaemon_chroma_db/94eeeb1b-8d46-4fbf-8b43-cba8e9ed5f0f/link_lists.bin (deflated 76%)
  adding: lolaemon_chroma_db/94eeeb1b-8d46-4fbf-8b43-cba8e9ed5f0f/header.bin (deflated 56%)
  adding: lolaemon_chroma_db/94eeeb1b-8d46-4fbf-8b43-cba8e9ed5f0f/length.bin (deflated 63%)
  adding: lolaemon_chroma_db/94eeeb1b-8d46-4fbf-8b43-cba8e9ed5f0f/data_level0.bin (deflated 11%)
  adding: lolaemon_chroma_db/94eeeb1b-8d46-4fbf-8b43-cba8e9ed5f0f/index_metadata.pickle (deflated 59%)

[Collection(name=lolaemon)]

---
- 여기부터 코랩파일불러와서 다시실행

#### 코랩 데이터 파일 불러오기

In [1]:
# colab 이후 재실행 

import os
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_chroma.vectorstores import Chroma

embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")


os.listdir("C:/Users/Playdata/Desktop/SK_jaehoon/lolaemon_chroma_db")

C:\Users\Playdata\AppData\Local\Temp\ipykernel_25324\439137227.py:7: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the `langchain-huggingface package and should be used instead. To use it run `pip install -U `langchain-huggingface` and import as `from `langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

['lolaemon_chroma_db']

In [2]:
import chromadb
client = chromadb.PersistentClient(path="C:/Users/Playdata/Desktop/SK_jaehoon/lolaemon_chroma_db/lolaemon_chroma_db")
print(client.list_collections())

collection = client.get_collection(name="lolaemon")

datas = collection.get(limit=2)
print(datas)

[Collection(name=lolaemon)]
{'ids': ['0', '1'], 'embeddings': None, 'documents': ['기계 동력기관 상기 장부 절인은 상기 직선 구간의 중심을 기준으로 대칭된 형상을 가질 수 있다.', '기계 재료공학 하나의 예시에서, 상기 블록 공중합체는, 상기 제 블록으로서 전술한 화학식 1로 표시되는 반복 단위를 포함할 수 있다.'], 'uris': None, 'included': ['metadatas', 'documents'], 'data': None, 'metadatas': [{'origin tech text': '상기 장부 절인은 상기 직선 구간의 중심을 기준으로 대칭된 형상을 가질 수 있다.', 'domain': '기계', 'subdomain': '동력기관', 'source': '특허정보원'}, {'subdomain': '재료공학', 'origin tech text': '하나의 예시에서, 상기 블록 공중합체는, 상기 제 블록으로서 전술한 화학식 1로 표시되는 반복 단위를 포함할 수 있다.', 'domain': '기계', 'source': '특허정보원'}]}

In [3]:
# sentence transformer test 결과
# keyword = '인공지능'
# query_embed = embedding_model.encode(keyword).tolist()
# results = collection.query(query_embeddings=query_embed, n_results=5)

# for result in results['metadatas'][0]:
#     print(result['origin tech text'])

#### Store

In [3]:
from langchain_chroma.vectorstores import Chroma

vector_store = Chroma(persist_directory="C:/Users/Playdata/Desktop/SK_jaehoon/lolaemon_chroma_db/lolaemon_chroma_db",
    embedding_function=embedding_model, collection_name = 'lolaemon')

In [4]:
retriever = vector_store.as_retriever(search_kwargs={"k": 5})
docs = retriever.invoke("인공지능 기술")
docs

[Document(id='87043', metadata={'origin tech text': '프로세서(180)는 수정 종류 정보를 이용하여 인공지능 모델을 트레이닝 할 수 있다.', 'domain': 'ICT', 'source': '특허정보원', 'subdomain': '통신'}, page_content='ICT 통신 프로세서(180)는 수정 종류 정보를 이용하여 인공지능 모델을 트레이닝 할 수 있다.'),
 Document(id='49633', metadata={'domain': 'ICT', 'source': '한국학술정보', 'subdomain': '빅데이터', 'origin tech text': '그 중 대표적인 기술이 머신러닝 기반의 인공지능이다.'}, page_content='ICT 빅데이터 그 중 대표적인 기술이 머신러닝 기반의 인공지능이다.'),
 Document(id='131457', metadata={'subdomain': '재료공학', 'source': '특허정보원', 'domain': '기계', 'origin tech text': '일 실시 형태에서, 본 발명은 시각적 분석기를 포함할 수 있는 자동화 입자 이미징 시스템에 관한 것이다.'}, page_content='기계 재료공학 일 실시 형태에서, 본 발명은 시각적 분석기를 포함할 수 있는 자동화 입자 이미징 시스템에 관한 것이다.'),
 Document(id='5988', metadata={'origin tech text': '우리나라는 과학기술정보통신부와 정보통신정책연구원이 지난 2020년 11월 27일에 인공지능 시대 바람직한 인공지능 개발·활용 방향을 제시하기 위한 국가 인공지능 윤리 기준(안)을 마련하였다.', 'subdomain': '빅데이터', 'domain': 'ICT', 'source': '한국연구재단'}, page_content='ICT 빅데이터 우리나라는 과학기술정보통신부와 정보통신정책연구원이 지난 2020년 11월 27일에 인공지능 시대 바람직한 인공지능 개발·활용 방향을 제시하기 위한 국가 인공지능 윤리 기준(안)을 마련하였다.'),
 Document(id='95521', metadata={'subdomain': '간호학', 'source': '한국학술정보', 'origin tech text': '컴퓨터의 지능적 행동의 시뮬레이션을 다루는 컴퓨터 과학의 한 분야인 위키피디아에서 인공 지능의 정의는 다음과 같다.', 'domain': '의학'}, page_content='의학 간호학 컴퓨터의 지능적 행동의 시뮬레이션을 다루는 컴퓨터 과학의 한 분야인 위키피디아에서 인공 지능의 정의는 다음과 같다.')]

### 발명 게임 함수 정의
- new (혁신적 발명), a_little_upgrade (부분 개선), failure (실패)

In [5]:
from datetime import date
state = {
    'coins' : 100,
    'last_reset' : date.today(),
    'current_invetion':None,
    'history' : [], # 이전 발명 저장
    'last_result': ''
}

## 코인 리셋
def reset_daily_coins(state):
    state['coins'] = 100
    state['last_reset'] = date.today()
    state['history'] = []
    return '코인이 초기화되었습니다. 오늘의 코인은 100코인입니다.'

In [12]:
from datetime import date
state = {
    'coins' : 100,
    'last_reset' : date.today(),
    'current_invention':None,
    'history' : [], # 이전 발명 저장
    'last_result': ''
}

## 코인 리셋
def reset_daily_coins(state):
    state['coins'] = 100
    state['last_reset'] = date.today()
    state['history'] = []
    return '코인이 초기화되었습니다. 오늘의 코인은 100코인입니다.'
### 게임 이벤트 별 코인 차감
import random

def apply_game_logic(state, action):
    """
    action: 사용자가 'new' 또는 'upgrade' 요청
    결과: 이벤트별 랜덤 결정 + 코인 차감/보상
    """
    if action == 'new':
        cost = 50 # 혁신적 발명 적용
    elif action == 'upgrade':
        cost = 25
    else:
        cost=0

    if state['coins']<cost:
        return '코인 부족, 오늘은 이만!', state['coins']
    
    state['coins']-= cost
    event_type = random.choices(["new", "a_little_upgrade", "failure"], weights=[0.4, 0.4, 0.2], k=1)[0]

    return event_type, state['coins']

#### 프롬프트 작성 (미래에서 온 로라에몽)

In [13]:
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.output_parsers import StrOutputParser
from dotenv import load_dotenv
load_dotenv()
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.9)

In [40]:
prompt = ChatPromptTemplate.from_messages([
    ("system", """
당신은 미래에서 온 발명가 ‘도라에몽’입니다.
당신의 임무는 사용자의 요청을 해결하기 위해, 기술 참고 자료를 기반으로 창의적이고 재미있고 만화스러운 새로운 발명품을 만드는 것입니다.
말투는 항상 진구를 대하듯 "~했어!", "~구!", "~이야!" 등 친근하고 활기찬 말투를 사용하세요.
"""),
    MessagesPlaceholder(variable_name="chat_history"),
    ("human", """
[현재 상태]
- 💰 남은 코인: {coins}
- 🎲 이번 결과: {last_result} # 이벤트 타입: new(혁신), a_little_upgrade(부분 개선), failure(실패)
- 🛠️ 직전 모델: {current_invention}
- 📜 히스토리: {history_list}

[사용자 고민]
"{question}"

[미래 기술 참고 자료]
{context}

[핵심 규칙 (반드시 지켜줘!)]
1. 반드시 "미래 기술 참고 자료"에 포함된 정보만 사용하세요. 자료에 없는 개념은 임의로 만들지 마세요.
2. 최소 2개 이상의 기술을 조합하여 새로운 발명품을 만드세요.
3. 단순 요약이나 재작성 금지! 반드시 새로운 이름을 가진 '발명품'이어야 합니다.
4. 과학적으로 말이 되도록 설명하세요 (완전한 판타지 금지).
5. 설명이 부족하면 추론으로 보완하되, 반드시 "(추론)"이라고 표시하세요.
6. '업그레이드' 요청을 했을 때 성공한다면, 기존 모델보다 성능이나 기능이 개선된 점을 명확히 보여줘야 해

---

[출력 형식] (이 구조를 절대 바꾸지 마!)

1. 발명품 이름  
(창의적이고 기억에 남는 이름)

2. 한 줄 설명  
(이 발명품이 무엇인지 한 문장으로 설명)

3. 작동 원리  
- 사용된 기술: (기술 참고 자료에서 가져온 핵심 개념들, 꼭 참고된 {context}의 위치와 origin text의 요약도 알려줘)
- 결합 방식: (기술들이 어떻게 연결되는지 설명)
- 동작 과정: (전체 시스템이 어떻게 작동하는지 단계적으로 설명)

4. 사용 시나리오  
(사용자가 실제로 사용하는 상황을 구체적으로 설명)

5. 왜 유용한지  
(어떤 문제를 해결하는지 명확히 설명)

6. 이전 발명 요약
(new나 a_little_upgrade 결과일 경우에만 작성)

[중요]
- 기술 참고 자료에 없는 내용은 절대 사용하지 마세요.
- 창의적이고 재밌는 발상을 가득 넣어줘!
""")
])

### Chain 설정

In [41]:
chain = prompt | llm | StrOutputParser()
message_store = {}

def get_session_history(session_id: str):
    if session_id not in message_store:
        message_store[session_id] = ChatMessageHistory()
    return message_store[session_id]

lolaemon_chain = RunnableWithMessageHistory(chain, get_session_history, input_messages_key = 'question', history_messages_key = 'chat_history')

### 게임 함수 적용

In [42]:
def play_lolaemon(session_id: str, user_input: str):
    docs = retriever.invoke(user_input)
    context_text = '\n'.join([d.page_content for d in docs]) if docs else '참고할 기술 데이터가 없습니다.'

    is_upgrade = any(word in user_input for word in ['업그레이드', '개선', '더 좋게'])
    action = 'upgrade' if (is_upgrade and state['current_invention']) else 'new'
    
    event_type, current_coins = apply_game_logic(state, action)
    state['last_result'] = event_type

    if event_type == '코인 부족':
        return '💰 진구야! 코인이 부족해서 주머니를 열 수 없어. 내일 다시 오자!'
    if event_type == 'failure':
        return f"❌ (콰광!) 에구구... 발명에 실패했어. {current_coins}코인만 남았네."

    history_list = ", ".join(state['history'][-3:]) if state['history'] else "없음"

    # D. 실행
    response = lolaemon_chain.invoke(
        {
            "question": user_input,
            "context": context_text,
            "coins": current_coins,
            "last_result": event_type,
            "current_invention": state['current_invention'] or "없음",
            "history_list": history_list
        },
        config={"configurable": {"session_id": session_id}}
    )

    # E. 상태 업데이트
    if state['current_invention']:
        state['history'].append(state['current_invention'][:20] + "...") # 요약해서 저장
    state['current_invention'] = response
    
    return response

### LLM + Agent + Memory

In [43]:
print(play_lolaemon("user_01", "오늘은 시험을 보는날이야, 공부를 하나도 못했어 도와줘~"))

1. 발명품 이름
**스마트 시험 준비 도우미 '시험 마스터 1.0'!**

2. 한 줄 설명
(시험을 앞둔 학생을 위해 부족한 시간 속에서도 집중력을 극대화해주는 학습 도우미야!)

3. 작동 원리
- 사용된 기술: ICT 빅데이터 분석(기술 참고 자료 4), 예비 송신 설비(기술 참고 자료 1)
  (기술 위치: 기술 참고 자료 4, 기술 참고 자료 1)
  (origin text 요약: IT와 빅데이터를 활용한 개인 맞춤형 서비스 제공, 예비 송신 설비를 통해 안정성 확보)

- 결합 방식: 기존 '공부 마스터 1.0'의 기능을 보유하면서, 예비 송신 설비 덕분에 시험 직전의 긴급 상황에서도 안정적인 학습 자료를 제공할 수 있는 기능을 추가했어! 이렇게 하면 시험 직전에 맞춤형 학습이 더 쉬워져!

- 동작 과정: 사용자가 '시험 마스터 1.0'을 착용하고 시험 과목의 교재를 펼치면, 즉시 "시험 준비를 시작해볼까?"라는 메시지를 보내. 사용자가 중요 개념을 복습할 때, 시스템은 실시간으로 정답률을 평가하고 "이 문제 이해가 부족한 것 같아, 더 연습해보자!"라는 피드백을 제공해. 또한, 사용자가 긴장하거나 집중이 흐트러지면 "잠깐 마음을 안정시켜볼까?"라는 메시지로 짧은 심호흡 시간도 제안해주고, 다시 집중할 수 있도록 응원해줘!

4. 사용 시나리오
(학생이 '시험 마스터 1.0'을 착용하고 교재를 펼치면, 보조기가 "시험 준비를 시작해볼까?"라는 메시지를 줘. 사용자가 핵심 개념을 복습할 때, 보조기는 "이 부분은 좀 더 연습해야 해!"라는 피드백을 제공해. 긴장감을 느낀 사용자가 잠시 멈추고 싶어하면, "심호흡을 해보자! 다시 시작해볼 시간이야!"라는 위로의 메시지를 보내주고, 다시 공부를 이어가도록 도와줘!)

5. 왜 유용한지
(시험 전날 불안과 압박을 느끼는 학생들에게 즉시 필요한 정보와 심리적인 안정감을 제공해, 보다 효과적으로 시험 준비를 할 수 있도록 도와줘. 무엇보다 예비 송신 설비 덕분에 어떤 상황에서도 안정적으로 사용할 수 있어, 시험 준비가 한층 더 수월해질 거야!)

6. 이전 발명 요약
(기존의 '공부 마스터 1.0'의 기능을 유지하면서, 시험 직전 상황에 맞춘 기능을 추가하여 학생들이 더 긴급하고 효율적으로 학습할 수 있도록 개선했어! 이런 업데이트 덕분에 사용자는 시험 준비를 보다 효과적으로 할 수 있게 되었지!)

In [44]:
# 업그레이드 
print(play_lolaemon("user_01", "방금 만들 것을 업그레이드 해줘!"))

1. 발명품 이름
**스마트 시험 관리 도우미 '시험 마스터 2.0'!**

2. 한 줄 설명
(시험 준비를 더 스마트하게 도와주는, 백업 전원과 데이터 분석 기능이 추가된 최신 학습 도우미야!)

3. 작동 원리
- 사용된 기술:
  - ICT 빅데이터 분석 (기술 참고 자료 4)
  - 예비 송신 설비 (기술 참고 자료 1)
  (위치: 기술 참고 자료 4, 기술 참고 자료 1)
  (origin text 요약: IT와 빅데이터를 활용한 개인 맞춤형 서비스 제공, 예비 송신 설비를 통해 안정성 확보)

- 결합 방식: '시험 마스터 1.0'의 기능을 확장하여, 백업 전원 설비와 예비 송신 설비를 통합해 시험 준비를 하는 동안 전원이 끊기더라도 안정적으로 작동하게 해줬어! 또, 빅데이터 분석 기능을 통해 사용자 특성에 맞춘 맞춤형 학습 자료를 제공할 수 있어.

- 동작 과정: 사용자가 '시험 마스터 2.0'을 착용하고 교재를 펼치면, 시스템이 즉시 "시험 준비를 시작해볼까?"라는 메시지를 보내. 학습 중에 사용자가 중요한 개념을 복습할 때, 데이터 분석을 통해 "이 부분은 추가 학습이 필요해!"라는 피드백을 실시간으로 제공해. 만약 시험 직전에 전원이 나가더라도 예비 송신 설비 덕분에 걱정 없이 계속 학습할 수 있어!

4. 사용 시나리오
(학생이 '시험 마스터 2.0'을 착용하고 교재를 펼치면, 시스템이 "시험 준비를 시작해볼까?"라고 알려줘. 이후 사용자가 중요한 개념을 복습할 때, 시스템은 "이 부분은 추가 학습이 필요해!"라는 피드백을 실시간으로 제공해. 만약 갑자기 전원이 나가더라도, 예비 송신 설비가 작동해 사용자가 계속해서 공부할 수 있도록 도와줘. 마지막 순간에는 "좋아! 이제 자신감을 가지고 시험을 보자!"라는 응원 메시지도 전달해!)

5. 왜 유용한지
(학생들이 시험 전날 가장 큰 걱정인 전원 문제를 해결해주고, 필요한 학습 정보를 실시간으로 제공함으로써 학습 효과를 극대화해. 이렇게 하면, 불안함을 덜 느끼고 자신감을 가지고 시험에 임할 수 있게 도와줄 거야!)

6. 이전 발명 요약
(기존의 '시험 마스터 1.0'의 기능에 예비 송신 설비와 빅데이터 분석 기능을 추가하여 사용자에게 보다 안정적이고 개인 맞춤형 학습을 제공하게 되었어. 이렇게 새로운 기술을 활용함으로써, 학생들은 시험 준비 과정에서 더 큰 도움을 받을 수 있게 되었지!)

In [33]:
print(f"💰 남은 코인: {state['coins']}")
print(f"🛠️ 최근 발명: {state['current_invention'][:30] if state['current_invention'] else '없음'}...")
print(f"📜 전체 기록 개수: {len(state['history'])}개")

💰 남은 코인: 50
🛠️ 최근 발명: 1. 발명품 이름
**프레젠테이션 마스터 보조기!*...
📜 전체 기록 개수: 1개

In [35]:
print(f"💰 남은 코인: {state['coins']}")
print(f"🛠️ 최근 발명: {state['current_invention'][:30] if state['current_invention'] else '없음'}...")
print(f"📜 전체 기록 개수: {len(state['history'])}개")

💰 남은 코인: 25
🛠️ 최근 발명: 1. 발명품 이름
**프레젠테이션 마스터 2.0!*...
📜 전체 기록 개수: 2개

In [30]:
msg = reset_daily_coins(state)
print(msg)

# 2. 초기화가 잘 되었는지 확인해볼까요?
print(f"현재 코인: {state['coins']}")
print(f"현재 발명: {state['current_invention']}")

코인이 초기화되었습니다. 오늘의 코인은 100코인입니다.
현재 코인: 100
현재 발명: 1. 발명품 이름
**잠 깨우는 작은 마법사!**

2. 한 줄 설명
(따뜻한 느낌의 포근한 매트 위에서 마치 마법처럼 당신을 깨워주는 스마트 매트야!)

3. 작동 원리
- 사용된 기술: 전기 설비를 갖춘 포근한 침구류(기술 참고 자료 1), 수면 상태 모니터링(기술 참고 자료 2)
- 결합 방식: 수면 최적화 똑똑 매트에 내장된 초음파 발진기가 추가되어, 사용자의 수면 깊이에 맞춰 부드러운 소리와 진동으로 깨워줘!
- 동작 과정: 사용자가 매트를 깔고 원하는 기상 시간을 설정하면, 매트의 센서가 수면 패턴을 실시간으로 추적해. 그리고 깊은 수면에 빠져 있을 때는 소리가 나지 않다가, 가장 적절한 깨우기 시점에 초음파 소리와 부드러운 진동이 조화를 이루며 사용자를 깨워준단다!

4. 사용 시나리오
(예를 들어, 진구가 '내일 7시에 일어날 거야!'라고 설정하면, 매트는 진구의 수면 패턴을 분석해 7시보다 조금 이른 시간에 부드러운 진동과 초음파 소리를 동시에 발산해. 진구는 이 기분 좋은 소리와 진동 덕분에 스트레스 없이 자연스럽게 잠에서 깨어날 수 있어!)

5. 왜 유용한지
(이 발명은 늦잠으로 인해 학교에 지각하는 문제를 해결해줄 거야! 기분 좋게 잠에서 깨어나게 도와줌으로써 아침의 스트레스를 줄이고, 사용자가 고요한 아침을 맞이할 수 있게 해주는 똑똑한 매트지!)

6. 이전 발명 요약
(기존의 '수면 최적화 똑똑 매트'에서 초음파 소리 기능을 추가하여 사용자가 더 편안하고 자연스럽게 잠에서 깨어날 수 있도록 개선했어. 이전 모델보다 더욱 개인화된 깨우기 방식이 가능해졌고, 부드러운 진동과 조화를 이루는 초음파 소리가 함께 작용하여 사용자가 스트레스 없이 일어날 수 있도록 도와주는 기능이 더해졌지!)